# Generated by Django 5.1.1 on 2024-10-03 18:06

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
