# Generated by Django 5.1.1 on 2024-10-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_favourite',
        ),
    ]
