# Generated by Django 5.1.1 on 2024-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_favourite_remove_slider_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
